-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 14:58:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema finalThesis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema finalThesis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finalThesis` DEFAULT CHARACTER SET utf8 ;
USE `finalThesis` ;

-- -----------------------------------------------------
-- Table `finalThesis`.`decision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalThesis`.`decision` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `goal` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finalThesis`.`criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalThesis`.`criteria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finalThesis`.`alternatives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalThesis`.`alternatives` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `finalThesis`.`participants`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `finalThesis`.`participants` (
--   `id` INT NOT NULL AUTO_INCREMENT,
--   `name` VARCHAR(45) NULL,
--   PRIMARY KEY (`id`))
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finalThesis`.`decision_criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalThesis`.`decision_criteria` (
  `decision_id` INT NOT NULL,
  `criteria_id` INT NOT NULL,
  `criterion_value` INT NULL,
  PRIMARY KEY (`decision_id`, `criteria_id`),
  INDEX `fk_decision_has_criteria_criteria1_idx` (`criteria_id` ASC),
  INDEX `fk_decision_has_criteria_decision_idx` (`decision_id` ASC),
  CONSTRAINT `fk_decision_has_criteria_decision`
    FOREIGN KEY (`decision_id`)
    REFERENCES `finalThesis`.`decision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_decision_has_criteria_criteria1`
    FOREIGN KEY (`criteria_id`)
    REFERENCES `finalThesis`.`criteria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finalThesis`.`decision_alternatives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalThesis`.`decision_alternatives` (
  `decision_id` INT NOT NULL,
  `alternatives_id` INT NOT NULL,
  `alternative_value` INT NULL,
  PRIMARY KEY (`decision_id`, `alternatives_id`),
  INDEX `fk_decision_has_alternatives_alternatives1_idx` (`alternatives_id` ASC),
  INDEX `fk_decision_has_alternatives_decision1_idx` (`decision_id` ASC),
  CONSTRAINT `fk_decision_has_alternatives_decision1`
    FOREIGN KEY (`decision_id`)
    REFERENCES `finalThesis`.`decision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_decision_has_alternatives_alternatives1`
    FOREIGN KEY (`alternatives_id`)
    REFERENCES `finalThesis`.`alternatives` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finalThesis`.`decision_participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalThesis`.`decision_participant` (
  `decision_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `participant_weight` INT NULL,
  `done` BIT NOT NULL
  PRIMARY KEY (`decision_id`, `user_id`),
  INDEX `fk_decision_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_decision_has_participants_decision1_idx` (`decision_id` ASC),
  CONSTRAINT `fk_decision_has_participants_decision1`
    FOREIGN KEY (`decision_id`)
    REFERENCES `finalThesis`.`decision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_decision_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `finalThesis`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `finalThesis`.`comparisons`
-- -----------------------------------------------------

CREATE TABLE Comparisons (
    id INTEGER PRIMARY KEY,
    decision_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    criterion_1_id INTEGER NOT NULL,
    criterion_2_id INTEGER NOT NULL,
    value INTEGER NOT NULL,
    FOREIGN KEY (decision_id) REFERENCES `finalThesis`.`decision` (`id`),
    FOREIGN KEY (user_id) REFERENCES `finalThesis`.`users` (`id`),
    FOREIGN KEY (criterion_1_id) REFERENCES `finalThesis`.`criteria` (`id`),
    FOREIGN KEY (criterion_2_id) REFERENCES `finalThesis`.`criteria` (`id`)
);


-- -----------------------------------------------------
-- Table `finalThesis`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalThesis`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
